version: '3'
services:
  sonarr:
    image: hotio/sonarr
    container_name: sonarr
    volumes:
      - ./media:/media
    ports:
      - 8989:8989

  radarr:
    image: hotio/radarr
    container_name: radarr
    volumes:
      - ./media:/media
    ports:
      - 7878:7878